### PR TITLE
Bring fork up to date

### PR DESCRIPTION
**Pull request by lantonov**
Syncing your new repository with the original. These are the steps
1. Press on "New pull request"
2. Below "Comparing changes" make base fork (to write into) tthsqe12/asmFish and head fork lantonov/asmFish. Use "switching the base" to make this. If this option is not available, switch manually.
3. Click the green “Create Pull Request” button. In the input fields that appear, give it a title like “Syncing from original”. Optionally, add a description.
4. Merge it with the “Merge Pull Request” button (and “Confirm Merge” afterwards), and you’re done!

### CODE REVIEW

**Comment by PanneMarion** [comment]
asmFishW_2017-01-22_bmi2   run only without LargePages 
with largePages Crash
Also pedantFishW_2017-01-22_bmi2

**Comment by lantonov** [comment]
The problem with large pages was fixed about 2 hours ago with this patch:
- fix bug where large page alloc must not fail
The latest compiles of 2017-01-22 have this fix and should not crash.

**Comment by PanneMarion** [comment]
THX
I test dounloud,15  after your aploud

Regards Matjaz Pirs Iccf GM and Fide FM

http://www.schachschule-pirs.com/
 
 
 
-------Originalmeldung-------
 
Von: Lyudmil Antonov
Datum: 22.01.2017 22:48:56
An: tthsqe12/asmFish
Cc: PanneMarion;  Comment
Betreff: Re: [tthsqe12/asmFish] Bring fork up to date (#1)
 
The problem with large pages was fixed about 2 hours ago with this patch:
fix bug where large page alloc must not fail
The latest compiles of 2017-01-22 have this fix and should not crash.

**Comment by lantonov** [comment]
Does it crash after the fix?

**Comment by PanneMarion** [comment]
No problem on 20, 16,or 12 core all best
Thx

 
 
-------Originalmeldung-------
 
Von: Lyudmil Antonov
Datum: 22.01.2017 23:00:17
An: tthsqe12/asmFish
Cc: PanneMarion;  Comment
Betreff: Re: [tthsqe12/asmFish] Bring fork up to date (#1)
 
Does it crash after the fix?

**Pull request merged**
